### ISSUE TITLE
Doesn't support tracks with multiple segments

### ISSUE THREAD

**Issue by LiddleDev** [urizev/j4gpx#1]
For example if a track has the following:

```
<trk>
    <trkseg>
        <trkpt lat="5.8834" lon="-1.42367">
            <time>2014-09-01T23:44:06Z</time>
        </trkpt>
        <trkpt lat="5.8834" lon="-1.42367">
            <time>2014-09-01T23:44:06Z</time>
        </trkpt>
    </trkseg>
    <trkseg>
        <trkpt lat="5.8834" lon="-1.42367">
            <time>2014-09-01T23:44:06Z</time>
        </trkpt>
    </trkseg>
</trk>
```

Then it will parse the track as only having the waypoints in the last segment.

You could fix this by instead of doing `setTrackPoints` on line 557 in GPXParser, create a method in Track called `addTrackPoints` and use that instead

Cheers

**Comment by urizev** [comment]
Thanks @Crayg!
I will fix it as you say.

**Comment by urizev** [comment]
New version 0.2 fixes the problem:

##### j4gpx-0.2 (2015-05-19)
- Track segment support. A segment is an list of waypoints. After parsing a segment adds all its waypoints to the track list waypoints and add a new segment to the track segment list.
- Add minimal test suite (needs to be completed)

It is possible to get the segments of a track with `Track.getTrackSegments()` method
